---
title: "HTS Households using Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
---

```{r global, context='data', include=FALSE}

devtools::load_all('C:/Users/matt.landis/OneDrive - Resource Systems Group, Inc/Git/tmrtools')

library(data.table)
library(leaflet)
library(DT)

# Create data -----------------------------------------------------------------

hh_labeled = readRDS('data/tnc_bayarea_hh_labeled.rds')
hh_map = hh_labeled[
  !income_aggregate %in% c('Prefer not to answer', 'Missing: Non-response', 'Missing: Skip logic') & !is.na(income_aggregate)]


# Define map palette  -------------------------------------------------------

income_levels = levels(factor(hh_map[, income_aggregate]))
pal = colorFactor(
  colorRampPalette(
    get_rsg_palette('hot')
    )(length(income_levels)),
  levels=income_levels)

# Function -----------------------------------------------------------------
# Get bounding box to filter data table as in this example
# https://github.com/Appsilon/crossfilter-demo/blob/master/app/app.R

in_bounding_box = function(data, bounds){
  
  cat('North bound:', bounds$north, ' max lat:', max(data$lat), '\n')
  cat('South bound:', bounds$south, ' min lat:', min(data$lat), '\n')
  cat('East bound:', bounds$east, ' max long:', max(data$long), '\n')
  cat('West bound:', bounds$west, ' min long:', min(data$long), '\n')
  
  data_filtered = data[
    reported_home_lon < bounds$east &
    reported_home_lon > bounds$west &
    reported_home_lat < bounds$north &
    reported_home_lat > bounds$south]
  
  cat('Nrow:', nrow(data_filtered), '\n')
  return(data_filtered)
  
}

```



Column {.sidebar}
-----------------------------------------------------------------------

Select income range(s) of interest

```{r, context='render'}

checkboxGroupInput(
  inputId="income",
  label = "Income",
  choices = income_levels, 
  selected = income_levels)
```



Column {data-width=500}
-----------------------------------------------------------------------

### Interactive maps with `leaflet`

```{r, context='render'}
leafletOutput(outputId='map')

```

```{r, context='server'}

data_filtered = reactive({
  hh_map[income_aggregate %in% input$income]
})

data_dt = reactive({
  if (is.null(input$map_bounds)){
    data_filtered()
  } else {
    bounds = input$map_bounds
    in_bounding_box(data_filtered(), bounds)
  }
})

output$map = renderLeaflet({
  
leaflet(data_dt()) %>%
  addTiles() %>%
  addCircleMarkers(
    lng=~reported_home_lon,
    lat=~reported_home_lat,
    stroke=FALSE,
    radius=5,
    fillOpacity=0.5,
    color=~pal(income_aggregate)) %>%
  addLegend(pal=pal, values=~income_aggregate, opacity=0.5)
  
})


```

Column {data-width=500}
-----------------------------------------------------------------------

### Interactive tables with `DT`

```{r, context='render'}
DTOutput(outputId='dt')
```

```{r, context='server'}

output$dt = renderDataTable({
  
  datatable(
    data=data_dt(),
    extensions="Scroller",
    style="bootstrap",
    class=c("display", "compact"),
    rownames=FALSE,
    width="100%",
    options=list(
      #deferRender=TRUE,
      scrollY='650px',
      scroller=TRUE,
      searching=TRUE)
  )
  
  
})
```

